application: helpapp-seproject
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: web/static

- url: /
  script: web.pages.index.app
  
- url: /index
  script: web.pages.index.app

- url: /helpSeeker
  script: web.pages.helpSeeker.app
  
- url: /volunteer
  script: web.pages.volunteer.app

- url: /connect
  script: web.pages.connect.app

- url: /add_request
  script: api.add_request.app

- url: /get_requests
  script: api.get_requests.app
  
- url: /setStatus
  script: api.setStatus.app
  
- url: /setCity
  script: api.setCity.app

- url: /get_notification
  script: api.get_notification.app

- url: /getUser
  script: api.getUser.app
  
- url: /update_user
  script: api.update_user.app
  
- url: /tasks/deleteRequests
  script: api.deleteRequests.app

- url: /api/(.*)
  script: api.\1.app


#add your url here.
  


libraries:
- name: webapp2
  version: "2.5.2"
