application: helpapp-seproject
version: 1-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: web/static

- url: /
  script: web.pages.index.app
  
- url: /index
  script: web.pages.index.app

- url: /api/(.*)
  script: api.\1.app


#add your url here.
  


libraries:
- name: webapp2
  version: "2.5.2"
